"""add new

Revision ID: ee7da96e9701
Revises: 762dce6dd899
Create Date: 2024-02-22 21:53:17.116418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7da96e9701'
down_revision: Union[str, None] = '762dce6dd899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocodes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promocodes', 'is_active')
    # ### end Alembic commands ###
